import { supabase } from "../supabaseClient";
import { ChallengeTrack } from "@/models";

// Create a new challenge track (id is generated by the server)
export async function createHackathonTrack(
    track: Omit<ChallengeTrack, "id">
): Promise<ChallengeTrack | null> {
    const { data, error } = await supabase
        .from('Challenge_Tracks')
        .insert(track)
        .select()
        .single();

    if (error) {
        console.error('Error creating hackathon track:', error);
        return null;
    }

    return data;
}