import { supabase } from "../supabaseClient";

import type { ChallengeTrack } from "@/models";


// ===============================
// POSTs
// ===============================

export interface CreateHackathonTrackRequest {
    name: string;
    challenge_description: string;
    hackathon_id: string;
}

// Create a new challenge track (id is generated by the server)
export async function createHackathonTrack(track: CreateHackathonTrackRequest): Promise<ChallengeTrack | null> {
    const { data, error } = await supabase
        .from('Challenge_Tracks')
        .insert(track)
        .select()
        .single();

    if (error) {
        console.error('Error creating hackathon track:', error);
        return null;
    }

    return data;
}


// ===============================
// PUTs
// ===============================

// Update an existing challenge track
export async function updateHackathonTrack(id: string, track: Partial<ChallengeTrack>): Promise<ChallengeTrack | null> {
    const { data, error } = await supabase
        .from('Challenge_Tracks')
        .update(track)
        .eq('id', id)
        .select()
        .single();

    if (error) {
        console.error('Error updating hackathon track:', error);
        return null;
    }

    return data;
}


// ===============================
// GETs
// ===============================

// Fetch all challenge tracks for a given hackathon
export async function getTracksForHackathon(hackathonId: string): Promise<ChallengeTrack[]> {
    const { data, error } = await supabase
        .from('Challenge_Tracks')
        .select('*')
        .eq('hackathon_id', hackathonId);

    if (error) {
        console.error('Error fetching hackathon tracks:', error);
        return [];
    }

    return data;
}